import S from '@sanity/desk-tool/structure-builder';
import {
    MdSettings,
    MdExtension,
    MdContactMail,
    MdVideoLibrary,
    MdPolymer,
    MdDonutSmall,
    MdBrokenImage,
    MdSpeakerNotes,
    MdChromeReaderMode,
    MdAlbum,
    MdNearMe,
    MdViewAgenda,
    MdFilter1,
} from 'react-icons/md';

const hiddenTypes = [
    'metadata',
    'contact',
    'video',
    'platforms',
    'solutions',
    'desk',
    'welcome',
    'brand',
    'hero',
    'menu',
    'carousel',
];

export default () =>
    S.list()
        .title('Content')
        .items([
            S.listItem()
                .title('Metadata')
                .icon(MdSettings)
                .child(S.editor().id('metadata').schemaType('metadata').documentId('metadata')),
            S.listItem()
                .title('Menu')
                .icon(MdNearMe)
                .child(S.editor().id('menu').schemaType('menu').documentId('menu')),

            S.listItem()
                .title('Pages')
                .icon(MdFilter1)
                .child(
                    S.list()
                        .title('Pages')
                        .items([
                            S.listItem()
                                .title('Contact')
                                .icon(MdContactMail)
                                .child(
                                    S.editor()
                                        .id('contact')
                                        .schemaType('contact')
                                        .documentId('contact'),
                                ),
                        ]),
                ),
            S.listItem()
                .title('Section')
                .icon(MdExtension)
                .child(
                    S.list()
                        .title('Section')
                        .items([
                            S.listItem()
                                .title('Video')
                                .icon(MdVideoLibrary)
                                .child(
                                    S.editor().id('video').schemaType('video').documentId('video'),
                                ),
                            S.listItem()
                                .title('Platforms')
                                .icon(MdPolymer)
                                .child(
                                    S.editor()
                                        .id('platforms')
                                        .schemaType('platforms')
                                        .documentId('platforms'),
                                ),
                            S.listItem()
                                .title('Solutions')
                                .icon(MdDonutSmall)
                                .child(
                                    S.editor()
                                        .id('solutions')
                                        .schemaType('solutions')
                                        .documentId('solutions'),
                                ),
                            S.listItem()
                                .title('Desk')
                                .icon(MdBrokenImage)
                                .child(S.editor().id('desk').schemaType('desk').documentId('desk')),
                            S.listItem()
                                .title('Welcome')
                                .icon(MdSpeakerNotes)
                                .child(
                                    S.editor()
                                        .id('welcome')
                                        .schemaType('welcome')
                                        .documentId('welcome'),
                                ),
                            S.listItem()
                                .title('Brand')
                                .icon(MdAlbum)
                                .child(
                                    S.editor().id('brand').schemaType('brand').documentId('brand'),
                                ),
                            S.listItem()
                                .title('Hero')
                                .icon(MdViewAgenda)
                                .child(S.editor().id('hero').schemaType('hero').documentId('hero')),
                            S.listItem()
                                .title('Carousel')
                                .icon(MdChromeReaderMode)
                                .child(
                                    S.editor()
                                        .id('carousel')
                                        .schemaType('carousel')
                                        .documentId('carousel'),
                                ),
                        ]),
                ),
            ...S.documentTypeListItems().filter(
                (listItem) => !hiddenTypes.includes(listItem.getId()),
            ),
        ]);
